// IDFM Train Pack
(function () {
	// Paris Metro
	/// Rail Metro
	window.SubwayBuilderAPI.trains.registerTrainType({
	    id: 'mf01',
	    name: 'MF 01',
	    description: 'A modern steel-wheel metro designed for Paris’s historic lines. Comfortable and efficient, it features full-width gangways and refrigerated ventilation.',
	    stats: {
        	maxSpeed: 19.44,             // m/s (≈70 kph)
        	maxAcceleration: 0.95,
        	maxDeceleration: 1,
        	maxLateralAcceleration: 0.9,
        	maxCantMm: 160,
        	maxCantDeficiencyMm: 135,
        	maxSlopePercentage: 5.5,
        	maxSpeedLocalStation: 8.5,   // m/s (≈30 kph)
        	crossoverSpeed: 6.95,        // m/s (≈25 kph)
        	yardSpeedLimit: 4.47,        // m/s (≈15 kph)
        	stopTimeSeconds: 30,
        	turnaroundTimeSeconds: 60,
        	minTurnRadius: 40,
        	minStationTurnRadius: 75,
        	parallelTrackSpacing: 3.2,
        	trackClearance: 1.2,
        	minCars: 5,
        	maxCars: 5,
        	carsPerCarSet: 5,
        	capacityPerCar: 158,
        	seatsPerCar: 18,
        	doorsPerCarPerSide: 3,
        	carLength: 15.12,
        	trainWidth: 2.4,
        	minStationLength: 78,
        	maxStationLength: 84,
        	carCost: 920_000,
        	baseTrackCost: 27_000,
        	baseStationCost: 65_000_000,
        	trainOperationalCostPerHour: 300,
        	carOperationalCostPerHour: 26,
        	trackMaintenanceCostPerMeter: 260,
        	stationMaintenanceCostPerYear: 200_000,
        	tphLimit: 40,
	    },
	    compatibleTrackTypes: ['mf01', 'mf19'],
	    appearance: { color: '#00C4B3', roofStyle: 'rounded', bodyColor: '#AEB0AD', couplerWidthMultiplier: 2 },
	    portalCost: 10_000_000,
	    rampCost: 4_000_000,
	    allowGradeCrossing: false,
	    maxOverpassSpan: 50,
	});
	window.SubwayBuilderAPI.trains.registerTrainType({
	    id: 'mf19',
	    name: 'MF 19',
	    description: 'The latest generation of steel-wheel metro designed to replace several ageing Paris Metro fleets. Modular in length and energy-efficient with regenerative braking. Exists in 4 and 5 cars configurations.',
	    stats: {
        	maxSpeed: 19.44,             // m/s (≈70 kph)
        	maxAcceleration: 0.95,
        	maxDeceleration: 1.1,
        	maxLateralAcceleration: 0.9,
        	maxCantMm: 160,
        	maxCantDeficiencyMm: 135,
        	maxSlopePercentage: 5.5,
        	maxSpeedLocalStation: 8.5,   // m/s (≈30 kph)
        	crossoverSpeed: 6.95,        // m/s (≈25 kph)
        	yardSpeedLimit: 4.47,        // m/s (≈15 kph)
        	stopTimeSeconds: 30,
        	turnaroundTimeSeconds: 60,
        	minTurnRadius: 40,
        	minStationTurnRadius: 75,
        	parallelTrackSpacing: 3.2,
        	trackClearance: 1.2,
        	minCars: 4,
        	maxCars: 5,
        	carsPerCarSet: 1,
        	capacityPerCar: 161,
        	seatsPerCar: 20,
        	doorsPerCarPerSide: 3,
        	carLength: 15.2,
        	trainWidth: 2.4,
        	minStationLength: 78,
        	maxStationLength: 84,
        	carCost: 1_400_000,
        	baseTrackCost: 27_000,
        	baseStationCost: 65_000_000,
        	trainOperationalCostPerHour: 260,
        	carOperationalCostPerHour: 23,
        	trackMaintenanceCostPerMeter: 260,
        	stationMaintenanceCostPerYear: 200_000,
        	tphLimit: 40,
	    },
	    compatibleTrackTypes: ['mf19', 'mf01'],
	    appearance: { color: '#00C4B3', roofStyle: 'rounded', bodyColor: '#D0D2D0', couplerWidthMultiplier: 2 },
	    portalCost: 10_000_000,
	    rampCost: 4_000_000,
	    maxOverpassSpan: 50,
	});
	/// Rubber Metro
	window.SubwayBuilderAPI.trains.registerTrainType({
	    id: 'mp89',
	    name: 'MP 89',
	    description: 'Rubber-tyred metro train existing in both automatic and manually driven versions. Its strong acceleration makes it particularly well suited to dense urban routes with closely spaced stations. Exists in 5 and 6 cars configurations.',
	    stats: {
        	maxSpeed: 22.22,             // m/s (≈80 kph)
        	maxAcceleration: 1.25,
        	maxDeceleration: 1.4,
        	maxLateralAcceleration: 0.9,
        	maxCantMm: 160,
        	maxCantDeficiencyMm: 135,
        	maxSlopePercentage: 8,
        	maxSpeedLocalStation: 22.22, // m/s (≈80 kph) because all stations have platform screens doors
        	crossoverSpeed: 6.95,        // m/s (≈25 kph)
        	yardSpeedLimit: 6.95,        // m/s (≈25 kph)
        	stopTimeSeconds: 30,
        	turnaroundTimeSeconds: 20,   // automatic metro
        	minTurnRadius: 40,
        	minStationTurnRadius: 75,
        	parallelTrackSpacing: 3.2,
        	trackClearance: 1.3,
        	minCars: 5,
        	maxCars: 6,
        	carsPerCarSet: 1,
        	capacityPerCar: 158,
        	seatsPerCar: 22,
        	doorsPerCarPerSide: 3,
        	carLength: 15.05,
        	trainWidth: 2.45,
        	minStationLength: 78,
        	maxStationLength: 128,
        	carCost: 1_000_000,
        	baseTrackCost: 35_000,
        	baseStationCost: 80_000_000,
        	trainOperationalCostPerHour: 120,
        	carOperationalCostPerHour: 28,
        	trackMaintenanceCostPerMeter: 300,
        	stationMaintenanceCostPerYear: 250_000,
        	tphLimit: 35,
	    },
	    compatibleTrackTypes: ['mp89', 'mp14'],
	    appearance: {color: '#640082', roofStyle: 'rounded', bodyColor: '#AEB0AD', couplerWidthMultiplier: 2 },
	    portalCost: 10_000_000,
	    rampCost: 4_000_000,
	    maxOverpassSpan: 50,
	});
	window.SubwayBuilderAPI.trains.registerTrainType({
	    id: 'mp14',
	    name: 'MP 14',
	    description: 'The latest generation of rubber-tyred metro trains in Paris, available in several train lengths and both automated and driver-operated versions. Its high-capacity configurations are designed for some of the busiest lines. Exists in 5, 6 and 8 cars configurations.',
	    stats: {
        	maxSpeed: 22.22,             // m/s (≈80 kph)
        	maxAcceleration: 1.35,
        	maxDeceleration: 1.4,
        	maxLateralAcceleration: 0.9,
        	maxCantMm: 160,
        	maxCantDeficiencyMm: 135,
        	maxSlopePercentage: 8,
        	maxSpeedLocalStation: 22.22, // m/s (≈80 kph) because all stations have platform screens doors
        	crossoverSpeed: 6.95,        // m/s (≈25 kph)
        	yardSpeedLimit: 6.95,        // m/s (≈25 kph)
        	stopTimeSeconds: 25,
        	turnaroundTimeSeconds: 20,   // automatic metro
        	minTurnRadius: 40,
        	minStationTurnRadius: 75,
        	parallelTrackSpacing: 3.2,
        	trackClearance: 1.3,
        	minCars: 5,
        	maxCars: 8,
        	carsPerCarSet: 1,
        	capacityPerCar: 160,
        	seatsPerCar: 24,
        	doorsPerCarPerSide: 3,
        	carLength: 15.05,
        	trainWidth: 2.45,
        	minStationLength: 78,
        	maxStationLength: 128,
        	carCost: 1_000_000,
        	baseTrackCost: 35_000,
        	baseStationCost: 80_000_000,
        	trainOperationalCostPerHour: 120,
        	carOperationalCostPerHour: 28,
        	trackMaintenanceCostPerMeter: 300,
        	stationMaintenanceCostPerYear: 250_000,
        	tphLimit: 42,
	    },
	    compatibleTrackTypes: ['mp14', 'mp89'],
	    appearance: {color: '#640082', roofStyle: 'boxy', bodyColor: '#D0D2D0', couplerWidthMultiplier: 2 },
	    portalCost: 10_000_000,
	    rampCost: 4_000_000,
	    maxOverpassSpan: 50,
	});
	/// GPE Metro
	window.SubwayBuilderAPI.trains.registerTrainType({
	    id: 'mr3v',
	    name: 'MR3V/MR6V',
	    description: 'The MR3V/MR6V is an automated steel-wheeled subway for the new Grand Paris Express lines 15-16-17. These three lines will be built to more modern standards. Exists in 3 and 6 cars configurations.',
	    stats: {
        	maxSpeed: 30.6,             // m/s (≈110 kph)
        	maxAcceleration: 1.1,
        	maxDeceleration: 1.2,
        	maxLateralAcceleration: 0.9,
        	maxCantMm: 160,
        	maxCantDeficiencyMm: 135,
        	maxSlopePercentage: 5.5,
        	maxSpeedLocalStation: 30.6,  // m/s (≈110 kph) because all stations have platform screens doors
        	crossoverSpeed: 6.95,        // m/s (≈25 kph)
        	yardSpeedLimit: 6.95,        // m/s (≈25 kph)
        	stopTimeSeconds: 30,
        	turnaroundTimeSeconds: 20,   // automatic metro
        	minTurnRadius: 40,
        	minStationTurnRadius: 500,
        	parallelTrackSpacing: 3.58,
        	trackClearance: 1.77,
        	minCars: 3,
        	maxCars: 6,
        	carsPerCarSet: 3,
        	seatsPerCar: 30,
        	doorsPerCarPerSide: 3,
        	capacityPerCar: 200,
        	carLength: 18,
        	trainWidth: 2.8,
        	minStationLength: 60,
        	maxStationLength: 120,
        	carCost: 920_000,
        	baseTrackCost: 48_875,
        	baseStationCost: 100_000_000,
        	trainOperationalCostPerHour: 120,
        	carOperationalCostPerHour: 18,
        	trackMaintenanceCostPerMeter: 300,
        	stationMaintenanceCostPerYear: 400_000,
        	tphLimit: 40,
	    },
	    compatibleTrackTypes: ['mr3v'],
	    appearance: {color: '#A50034', roofStyle: 'rounded', bodyColor: '#D0D2D0', couplerWidthMultiplier: 2, catenary: true},
	    portalCost: 15_000_000,
	    rampCost: 5_000_000,
	    maxOverpassSpan: 150,
	});
	// Paris RER&TRANSILIEN
	/// RER A
	window.SubwayBuilderAPI.trains.registerTrainType({
	    id: 'mi09',
	    name: 'MI 09',
	    description: 'Double-deck EMU designed to handle high passenger volumes. It combines high capacity, strong acceleration and numerous doors for rapid passenger exchange needed on the Line A.',
	    stats: {
        	maxSpeed: 33.33,             // m/s (≈120 kph)
        	maxAcceleration: 1.2,
        	maxDeceleration: 1.35,
        	maxLateralAcceleration: 1,
        	maxCantMm: 160,
        	maxCantDeficiencyMm: 150,
        	maxSlopePercentage: 4,
        	maxSpeedLocalStation: 13.88, // m/s (≈50 kph)
        	crossoverSpeed: 6.95,        // m/s (≈25 kph)
        	yardSpeedLimit: 6.95,        // m/s (≈25 kph)
        	stopTimeSeconds: 30,
        	turnaroundTimeSeconds: 120,
        	minTurnRadius: 150,
        	minStationTurnRadius: 500,
        	parallelTrackSpacing: 3.5,
        	trackClearance: 2.1,
        	minCars: 5,
        	maxCars: 10,
        	carsPerCarSet: 5,
        	capacityPerCar: 345,
        	seatsPerCar: 94,
        	doorsPerCarPerSide: 6,           // to represent the 3 gigantic double-doors per side
        	carLength: 22.4,
        	trainWidth: 2.9,
        	minStationLength: 115,
        	maxStationLength: 230,
        	carCost: 3_800_000,
        	baseTrackCost: 28_000,
        	baseStationCost: 40_000_000,
        	trainOperationalCostPerHour: 650,
        	carOperationalCostPerHour: 55,
        	trackMaintenanceCostPerMeter: 320,
        	stationMaintenanceCostPerYear: 200_000,
        	tphLimit: 40,
	    },
	    compatibleTrackTypes: ['mi09', 'francilien'],
	    appearance: {color: '#FF1400', roofStyle: 'boxy', bodyColor: '#AEB0AD', couplerWidthMultiplier: 2, catenary: true},
	    portalCost: 15_000_000,
	    rampCost: 5_000_000,
	    maxOverpassSpan: 150,
	    allowGradeCrossing: true,
	    gradeCrossingBaseCost: 200_000,
	    gradeCrossingMaintenancePerDay: 2_500,
	    gradeCrossingTphLimit: {
		highway: null,
		major: 14,
		medium: 20,
		minor: 30,
    	},
	})
	/// RER B
	window.SubwayBuilderAPI.trains.registerTrainType({
	    id: 'mi84',
	    name: 'MI 84',
	    description: 'Dual-voltage EMU designed to operate seamlessly across both RATP and SNCF networks on line B.',
	    stats: {
        	maxSpeed: 33.33,             // m/s (≈120 kph)
        	maxAcceleration: 1,
        	maxDeceleration: 1.2,
        	maxLateralAcceleration: 1,
        	maxCantMm: 160,
        	maxCantDeficiencyMm: 150,
        	maxSlopePercentage: 4,
        	maxSpeedLocalStation: 13.88, // m/s (≈50 kph)
        	crossoverSpeed: 6.95,        // m/s (≈25 kph)
        	yardSpeedLimit: 6.95,        // m/s (≈25 kph)
        	stopTimeSeconds: 40,
        	turnaroundTimeSeconds: 120,
        	minTurnRadius: 150,
        	minStationTurnRadius: 500,
        	parallelTrackSpacing: 3.5,
        	trackClearance: 2.1,
        	minCars: 4,
        	maxCars: 8,
        	carsPerCarSet: 4,
        	capacityPerCar: 212,
        	seatsPerCar: 78,
        	doorsPerCarPerSide: 4,
        	carLength: 26,
        	trainWidth: 2.8,
        	minStationLength: 110,
        	maxStationLength: 220,
        	carCost: 2_400_000,
        	baseTrackCost: 28_000,
        	baseStationCost: 40_000_000,
        	trainOperationalCostPerHour: 500,
        	carOperationalCostPerHour: 45,
        	trackMaintenanceCostPerMeter: 280,
        	stationMaintenanceCostPerYear: 160_000,
        	tphLimit: 40,
	    },
	    compatibleTrackTypes: ['mi84', 'mi20', 'mi09', 'z2n', 'rerng', 'francilien'],
	    appearance: {color: '#3C91DC', roofStyle: 'boxy', bodyColor: '#AEB0AD', couplerWidthMultiplier: 2, catenary: true},
	    portalCost: 15_000_000,
	    rampCost: 5_000_000,
	    maxOverpassSpan: 150,
	    allowGradeCrossing: true,
	    gradeCrossingBaseCost: 200_000,
	    gradeCrossingMaintenancePerDay: 2_500,
	    gradeCrossingTphLimit: {
		highway: null,
		major: 14,
		medium: 20,
		minor: 30,
    	},
	})
	window.SubwayBuilderAPI.trains.registerTrainType({
	    id: 'mi20',
	    name: 'MI 20',
	    description: 'The replacement of the MI 84, this new generation EMU will increase capacity and accessibility of the RER B and adding a second floor on half of the cars.',
	    stats: {
        	maxSpeed: 33.33,             // m/s (≈120 kph)
        	maxAcceleration: 1.2,
        	maxDeceleration: 1.35,
        	maxLateralAcceleration: 1,
        	maxCantMm: 160,
        	maxCantDeficiencyMm: 150,
        	maxSlopePercentage: 4,
        	maxSpeedLocalStation: 13.88, // m/s (≈50 kph)
        	crossoverSpeed: 6.95,        // m/s (≈25 kph)
        	yardSpeedLimit: 6.95,        // m/s (≈25 kph)
        	stopTimeSeconds: 40,
        	turnaroundTimeSeconds: 120,
        	minTurnRadius: 150,
        	minStationTurnRadius: 500,
        	parallelTrackSpacing: 3.5,
        	trackClearance: 2.1,
        	minCars: 7,
        	maxCars: 14,
        	carsPerCarSet: 7,
        	capacityPerCar: 152,
        	seatsPerCar: 48,
        	doorsPerCarPerSide: 2,
        	carLength: 14.87,
        	trainWidth: 3,
        	minStationLength: 110,
        	maxStationLength: 220,
        	carCost: 2_790_000,
        	baseTrackCost: 28_000,
        	baseStationCost: 40_000_000,
        	trainOperationalCostPerHour: 550,
        	carOperationalCostPerHour: 45,
        	trackMaintenanceCostPerMeter: 280,
        	stationMaintenanceCostPerYear: 160_000,
        	tphLimit: 40,
	    },

	    compatibleTrackTypes: ['mi20', 'mi84', 'mi09', 'z2n', 'rerng', 'francilien'],
	    appearance: {color: '#3C91DC', roofStyle: 'rounded', bodyColor: '#D0D2D0', couplerWidthMultiplier: 2, catenary: true},
	    portalCost: 15_000_000,
	    rampCost: 5_000_000,
	    maxOverpassSpan: 150,
	    allowGradeCrossing: true,
	    gradeCrossingBaseCost: 200_000,
	    gradeCrossingMaintenancePerDay: 2_500,
	    gradeCrossingTphLimit: {
		highway: null,
		major: 14,
		medium: 20,
		minor: 30,
    	},
	})
	/// RER C+TRANSILIEN
	window.SubwayBuilderAPI.trains.registerTrainType({
	    id: 'z2n',
	    name: 'Z 2N',
	    description: 'A family of double-decker EMU, improved over the years. Robust, spacious and fast, it is adapted to longer distances between stations. Exists in 4 and 5 cars configurations',
	    stats: {
        	maxSpeed: 38.90,             // m/s (≈140 kph)
        	maxAcceleration: 1,
        	maxDeceleration: 1.05,
        	maxLateralAcceleration: 1,
        	maxCantMm: 160,
        	maxCantDeficiencyMm: 150,
        	maxSlopePercentage: 3.5,
        	maxSpeedLocalStation: 13.88, // m/s (≈50 kph)
        	crossoverSpeed: 6.95,        // m/s (≈25 kph)
        	yardSpeedLimit: 6.95,        // m/s (≈25 kph)
        	stopTimeSeconds: 50,
        	turnaroundTimeSeconds: 120,
        	minTurnRadius: 150,
        	minStationTurnRadius: 500,
        	parallelTrackSpacing: 3.5,
        	trackClearance: 2.1,
        	minCars: 4,
        	maxCars: 10,
        	carsPerCarSet: 1,
        	capacityPerCar: 400,
        	seatsPerCar: 89,
        	doorsPerCarPerSide: 2,
        	carLength: 25.9,
        	trainWidth: 2.9,
        	minStationLength: 112,
        	maxStationLength: 280,
        	carCost: 2_200_000,
        	baseTrackCost: 28_000,
        	baseStationCost: 40_000_000,
        	trainOperationalCostPerHour: 400,
        	carOperationalCostPerHour: 40,
        	trackMaintenanceCostPerMeter: 280,
        	stationMaintenanceCostPerYear: 160_000,
        	tphLimit: 40,
	    },
	    compatibleTrackTypes: ['z2n', 'rerng', 'francilien'],
	    appearance: {color: '#FFBE00', roofStyle: 'boxy', bodyColor: '#AEB0AD', couplerWidthMultiplier: 2, catenary: true},
	    portalCost: 15_000_000,
	    rampCost: 5_000_000,
	    maxOverpassSpan: 150,
	    allowGradeCrossing: true,
	    gradeCrossingBaseCost: 200_000,
	    gradeCrossingMaintenancePerDay: 2_500,
	    gradeCrossingTphLimit: {
		highway: null,
		major: 14,
		medium: 20,
		minor: 30,
    	},
	})
	/// RER D/E
	window.SubwayBuilderAPI.trains.registerTrainType({
	    id: 'rerng',
	    name: 'RER NG',
	    description: 'The new generation of double-deck EMU; high capacity and strong acceleration allow it to combine suburban-rail performance with intensive urban operations. Exists in 6 and 7 cars configurations.',
	    stats: {
        	maxSpeed: 38.90,             // m/s (≈140 kph)
        	maxAcceleration: 1.18,
        	maxDeceleration: 1.15,
        	maxLateralAcceleration: 1,
        	maxCantMm: 160,
        	maxCantDeficiencyMm: 150,
        	maxSlopePercentage: 4,
        	maxSpeedLocalStation: 13.88, // m/s (≈50 kph)
        	crossoverSpeed: 6.95,        // m/s (≈25 kph)
        	yardSpeedLimit: 6.95,        // m/s (≈25 kph)
        	stopTimeSeconds: 45,
        	turnaroundTimeSeconds: 120,
        	minTurnRadius: 150,
        	minStationTurnRadius: 500,
        	parallelTrackSpacing: 3.5,
        	trackClearance: 2.1,
        	minCars: 6,
        	maxCars: 14,
        	carsPerCarSet: 1,
        	capacityPerCar: 260,
			seatsPerCar: 85,
			doorsPerCarPerSide: 2,
        	carLength: 18.6,
        	trainWidth: 3,
        	minStationLength: 115,
        	maxStationLength: 280,
        	carCost: 3_150_000,
        	baseTrackCost: 28_000,
        	baseStationCost: 40_000_000,
        	trainOperationalCostPerHour: 450,
        	carOperationalCostPerHour: 35,
        	trackMaintenanceCostPerMeter: 280,
        	stationMaintenanceCostPerYear: 160_000,
        	tphLimit: 40,
	    },
	    compatibleTrackTypes: ['rerng', 'z2n', 'francilien'],
	    appearance: {color: '#00643C', roofStyle: 'boxy', bodyColor: '#D0D2D0', couplerWidthMultiplier: 2, catenary: true},
	    portalCost: 15_000_000,
	    rampCost: 5_000_000,
	    maxOverpassSpan: 150,
	    allowGradeCrossing: true,
	    gradeCrossingBaseCost: 200_000,
	    gradeCrossingMaintenancePerDay: 2_500,
	    gradeCrossingTphLimit: {
		highway: null,
		major: 14,
		medium: 20,
		minor: 30,
    	},
	})
	/// TRANSILIEN
	window.SubwayBuilderAPI.trains.registerTrainType({
	    id: 'francilien',
	    name: 'Francilien',
	    description: 'Modern suburban EMU recognizable by its unusually wide body and spacious interior. It is optimized for frequent-stop Transilien services while retaining strong performance on longer suburban sections but has only 1 door per car making dwell time longer. Exists in 7 and 8 cars configurations',
	    stats: {
        	maxSpeed: 38.89,             // m/s (≈140 kph)
        	maxAcceleration: 1,
        	maxDeceleration: 1.25,
        	maxLateralAcceleration: 1,
        	maxCantMm: 160,
        	maxCantDeficiencyMm: 150,
        	maxSlopePercentage: 3.5,
        	maxSpeedLocalStation: 13.88, // m/s (≈50 kph)
        	crossoverSpeed: 6.95,        // m/s (≈25 kph)
        	yardSpeedLimit: 6.95,        // m/s (≈25 kph)
        	stopTimeSeconds: 30,
        	turnaroundTimeSeconds: 120,
        	minTurnRadius: 150,
        	minStationTurnRadius: 500,
        	parallelTrackSpacing: 3.5,
        	trackClearance: 2.1,
        	minCars: 7,
        	maxCars: 16,
        	carsPerCarSet: 1,
        	capacityPerCar: 132,
			seatsPerCar: 62,
			doorsPerCarPerSide: 1,
        	carLength: 13.4,
        	trainWidth: 3.06,
        	minStationLength: 95,
        	maxStationLength: 280,
        	carCost: 2_000_000,
        	baseTrackCost: 28_000,
        	baseStationCost: 40_000_000,
        	trainOperationalCostPerHour: 360,
        	carOperationalCostPerHour: 35,
        	trackMaintenanceCostPerMeter: 280,
        	stationMaintenanceCostPerYear: 160_000,
        	tphLimit: 40,
	    },
	    compatibleTrackTypes: ['francilien', 'rerng', 'z2n', 'mi09'],
	    appearance: {color: '#D282BE', roofStyle: 'boxy', bodyColor: '#BFC1BE', couplerWidthMultiplier: 2, catenary: true},
	    portalCost: 15_000_000,
	    rampCost: 5_000_000,
	    maxOverpassSpan: 150,
	    allowGradeCrossing: true,
	    gradeCrossingBaseCost: 200_000,
	    gradeCrossingMaintenancePerDay: 2_500,
	    gradeCrossingTphLimit: {
		highway: null,
		major: 14,
		medium: 20,
		minor: 30,
    	},
	})
	// LIGHT RAIL
	window.SubwayBuilderAPI.trains.registerTrainType({
	    id: 'dualis',
	    name: 'Dualis',
	    description: 'A versatile tram-train designed to operate both on conventional railway and tramway sections. Fully low-floor, strong gradients and higher speed make it suitable for mixed urban and suburban routes.',
	    stats: {
        	maxSpeed: 27.78,             // m/s (≈100 kph)
        	maxAcceleration: 1.1,
        	maxDeceleration: 1.2,
        	maxLateralAcceleration: 0.7,
        	maxCantMm: 60,
        	maxCantDeficiencyMm: 100,
        	maxSlopePercentage: 6,
        	maxSpeedLocalStation: 13.88, // m/s (≈50 kph)
        	crossoverSpeed: 6.95,        // m/s (≈25 kph)
        	yardSpeedLimit: 6.95,        // m/s (≈25 kph)
        	stopTimeSeconds: 30,
        	turnaroundTimeSeconds: 60,
        	minTurnRadius: 25,
        	minStationTurnRadius: 35,
        	parallelTrackSpacing: 3,
        	trackClearance: 0.75,
        	minCars: 4,
        	maxCars: 6,
        	carsPerCarSet: 2,
        	capacityPerCar: 64,
        	seatsPerCar: 24,
        	doorsPerCarPerSide: 1,
        	carLength: 10.4,
        	trainWidth: 2.65,
        	minStationLength: 45,
        	maxStationLength: 70,
        	carCost: 1_850_000,
        	baseTrackCost: 23_000,
        	baseStationCost: 15_000_000,
        	trainOperationalCostPerHour: 180,
        	carOperationalCostPerHour: 30,
        	trackMaintenanceCostPerMeter: 180,
        	stationMaintenanceCostPerYear: 60_000,
        	tphLimit: 30,
	    },
	    compatibleTrackTypes: ['dualis', 'citadis', 'tram', 'light-rail', 'z2n', 'francilien', 'rerng'],
	    appearance: {color: '#6E6E00', roofStyle: 'boxy', bodyColor: '#BFC1BE', couplerWidthMultiplier: 2, catenary: true},
	    portalCost: 6_000_000,
	    rampCost: 3_000_000,
	    maxOverpassSpan: 150,
	    allowGradeCrossing: true,
	    gradeCrossingBaseCost: 100_000,
	    gradeCrossingMaintenancePerDay: 1_000,
	    gradeCrossingTphLimit: {
		highway: null,
		major: 20,
		medium: 30,
		minor: 30,
    	},
	})
	window.SubwayBuilderAPI.trains.registerTrainType({
	    id: 'citadis',
	    name: 'Citadis X05',
	    description: 'A modern tram designed for intensive urban operation. Its numerous doors and low-floor layout prioritize accessibility and rapid passenger exchange. Exists in different lengths for higher capacity corridors.',
	    stats: {
        	maxSpeed: 19.44,             // m/s (≈70 kph)
        	maxAcceleration: 1.2,
        	maxDeceleration: 1.25,
        	maxLateralAcceleration: 0.7,
        	maxCantMm: 60,
        	maxCantDeficiencyMm: 100,
        	maxSlopePercentage: 6,
        	maxSpeedLocalStation: 6.95,  // m/s (≈25 kph)
        	crossoverSpeed: 6.95,        // m/s (≈25 kph)
        	yardSpeedLimit: 6.95,        // m/s (≈25 kph)
        	stopTimeSeconds: 20,
        	turnaroundTimeSeconds: 60,
        	minTurnRadius: 25,
        	minStationTurnRadius: 35,
        	parallelTrackSpacing: 3,
        	trackClearance: 0.75,
        	minCars: 5,
        	maxCars: 7,
        	carsPerCarSet: 1,
        	capacityPerCar: 45,
        	seatsPerCar: 12,
        	doorsPerCarPerSide: 1,
        	carLength: 6.3,
        	trainWidth: 2.65,
        	minStationLength: 36,
        	maxStationLength: 50,
        	carCost: 800_000,
        	baseTrackCost: 18_000,
        	baseStationCost: 12_000_000,
        	trainOperationalCostPerHour: 160,
        	carOperationalCostPerHour: 22,
        	trackMaintenanceCostPerMeter: 150,
        	stationMaintenanceCostPerYear: 40_000,
        	tphLimit: 30,
	    },
	    compatibleTrackTypes: ['citadis', 'tram'],
	    appearance: {color: '#0055C8', roofStyle: 'rounded', bodyColor: '#BFC1BE', couplerWidthMultiplier: 2, catenary: true},
	    portalCost: 4_000_000,
	    rampCost: 2_000_000,
	    maxOverpassSpan: 150,
	    allowGradeCrossing: true,
	    gradeCrossingBaseCost: 100_000,
	    gradeCrossingMaintenancePerDay: 1_000,
	    gradeCrossingTphLimit: {
		highway: null,
		major: 20,
		medium: 30,
		minor: 30,
    	},
	})
	// AIRVAL
	window.SubwayBuilderAPI.trains.registerTrainType({
	    id: 'val',
	    name: 'VAL 206/208',
	    description: 'VAL is a compact, fully automated rubber-tyred transit system, combining high frequency, strong acceleration and flexible alignment for dedicated urban and airport links.',
	    stats: {
        	maxSpeed: 22.22,             // m/s (≈80 kph)
        	maxAcceleration: 1.35,
        	maxDeceleration: 1.35,
        	maxLateralAcceleration: 0.9,
        	maxCantMm: 160,
        	maxCantDeficiencyMm: 135,
        	maxSlopePercentage: 8,
        	maxSpeedLocalStation: 19.44, // m/s (≈70 kph) because all stations have platform screens doors
        	crossoverSpeed: 6.95,        // m/s (≈25 kph)
        	yardSpeedLimit: 4.16,        // m/s (≈15 kph)
        	stopTimeSeconds: 20,
        	turnaroundTimeSeconds: 30,
        	minTurnRadius: 30,
        	minStationTurnRadius: 100,
        	parallelTrackSpacing: 3,
        	trackClearance: 1.3,
        	minCars: 2,
        	maxCars: 4,
        	carsPerCarSet: 2,
        	capacityPerCar: 100,
        	seatsPerCar: 20,
        	doorsPerCarPerSide: 3,
        	carLength: 13,
        	trainWidth: 2.06,
        	minStationLength: 30,
        	maxStationLength: 60,
        	carCost: 2_200_000,
        	baseTrackCost: 24000,
        	baseStationCost: 30000000,
        	trainOperationalCostPerHour: 250,
        	carOperationalCostPerHour: 32,
        	trackMaintenanceCostPerMeter: 220,
        	stationMaintenanceCostPerYear: 130000,
        	tphLimit: 38,
	    },
	    compatibleTrackTypes: ['val'],
	    appearance: {color: '#6EC4E8', roofStyle: 'boxy', bodyColor: '#FFFFFF'},
	    portalCost: 4_000_000,
	    rampCost: 2_000_000,
	    maxOverpassSpan: 80,
	    allowGradeCrossing: false,
	})
})();
